-- v6: 핫카드 + 검색 로그 + 업데이트 요청 + API 로그
-- 기존 테이블 무영향. 모두 신규 테이블 추가만.

-- 1. 사용자 검색 로그
create table if not exists public.card_search_logs (
  id bigint generated by default as identity primary key,
  query text not null,
  normalized_query text,
  matched_slug text references public.cards(slug),
  game text,
  result_count int default 0,
  has_price boolean default false,
  user_agent text,
  ip_hash text,
  created_at timestamptz default now()
);
create index if not exists csl_normalized_idx on public.card_search_logs (normalized_query, created_at desc);
create index if not exists csl_slug_idx on public.card_search_logs (matched_slug);
create index if not exists csl_date_idx on public.card_search_logs (created_at desc);
alter table public.card_search_logs enable row level security;
drop policy if exists csl_insert_anon on public.card_search_logs;
create policy csl_insert_anon on public.card_search_logs for insert with check (true);

-- 2. 가격 업데이트 요청 큐
create table if not exists public.price_update_requests (
  id bigint generated by default as identity primary key,
  card_slug text references public.cards(slug),
  query text,
  request_count int default 1,
  last_requested_at timestamptz default now(),
  status text default 'pending' check (status in ('pending','queued','done','failed','skipped')),
  resolved_at timestamptz,
  notes text,
  created_at timestamptz default now()
);
create unique index if not exists pur_slug_uniq on public.price_update_requests (card_slug) where card_slug is not null;
create index if not exists pur_status_idx on public.price_update_requests (status, last_requested_at desc);
alter table public.price_update_requests enable row level security;
drop policy if exists pur_select_all on public.price_update_requests;
create policy pur_select_all on public.price_update_requests for select using (true);

-- 3. 핫카드 (일별 스냅샷)
create table if not exists public.hot_cards (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  card_slug text references public.cards(slug),
  game text,
  category text not null,  -- 'top','rising_7d','rising_30d','requested','search_surge','editor_pick'
  rank int not null,
  hot_score numeric,
  price_change_score numeric default 0,
  search_score numeric default 0,
  request_score numeric default 0,
  new_release_score numeric default 0,
  editor_score numeric default 0,
  reason text,
  created_at timestamptz default now()
);
create unique index if not exists hc_unique on public.hot_cards (date, game, category, rank);
create index if not exists hc_date_cat_idx on public.hot_cards (date desc, category, rank);
alter table public.hot_cards enable row level security;
drop policy if exists hc_select_all on public.hot_cards;
create policy hc_select_all on public.hot_cards for select using (true);

-- 4. API 업데이트 로그
create table if not exists public.api_update_logs (
  id bigint generated by default as identity primary key,
  source text not null,        -- 'pokemontcg-api','tcgcsv'
  job_name text,                -- 'daily-top-2000','cron-prune' 등
  status text not null,         -- 'started','completed','failed','rate_limited','partial'
  requested_count int default 0,
  updated_count int default 0,
  failed_count int default 0,
  api_calls_used int default 0,
  error_message text,
  started_at timestamptz default now(),
  finished_at timestamptz
);
create index if not exists aul_source_date_idx on public.api_update_logs (source, started_at desc);
alter table public.api_update_logs enable row level security;
drop policy if exists aul_select_all on public.api_update_logs;
create policy aul_select_all on public.api_update_logs for select using (true);

-- 5. 운영자 가중치 (Editor pick) — cards 보강
do $$ begin
  alter table public.cards add column if not exists editor_score numeric default 0;
  alter table public.cards add column if not exists editor_note text;
exception when others then null;
end $$;

-- 6. 카드별 보조 가격 메트릭 (외부 API의 avg7/avg30 보관)
create table if not exists public.price_metrics_external (
  card_slug text primary key references public.cards(slug),
  source text not null,
  ext_avg_24h numeric,
  ext_avg_7d numeric,
  ext_avg_14d numeric,
  ext_avg_30d numeric,
  ext_avg_90d numeric,
  ext_change_24h_pct numeric,
  ext_change_7d_pct numeric,
  ext_change_30d_pct numeric,
  ext_change_90d_pct numeric,
  ext_currency text,
  ext_updated_at timestamptz,
  updated_at timestamptz default now()
);
alter table public.price_metrics_external enable row level security;
drop policy if exists pme_select_all on public.price_metrics_external;
create policy pme_select_all on public.price_metrics_external for select using (true);

grant select on public.card_search_logs, public.price_update_requests, public.hot_cards,
                 public.api_update_logs, public.price_metrics_external
  to anon, authenticated;
grant insert on public.card_search_logs to anon, authenticated;
